export enum Api {
  getClient = '/userClient/getClient',
  getBalance= '/balance/getBalanceByClientIdAndCurrency',
  getShops = '/shippingInvoice/shopsByClient',
  getShopOptions = '/shopOptions/findByClientId',
  getOrdersByShop = '/business/platformOrder/ordersByShop',
  postOrders = '/business/platformOrder/orderManagement',
  getRecipientInfo = '/business/platformOrder/recipientInfo',
  getSelfServiceClients = "/userClient/getSelfServiceClients",
  getOrderStatusByShop = "/shippingInvoice/preShipping/ordersStatusByShops",
  completeFeesEstimation = '/shippingInvoice/completeFeesEstimation',
  makeManualShippingInvoice = "/shippingInvoice/makeManualInvoice",
  makeManualPurchaseInvoice = "/shippingInvoice/makeManualPurchaseInvoice",
  makeCompleteManualInvoice = "/shippingInvoice/makeManualComplete",
  makeShippingInvoice= '/shippingInvoice/make',
  makeCompleteShippingInvoice= '/shippingInvoice/makeComplete',
  downloadInvoice = "/shippingInvoice/download",
  downloadPdf = "/generated/shippingInvoice/downloadPdf",
  downloadInvoiceDetail = "/shippingInvoice/downloadInvoiceDetail",
  getValidOrderTimePeriod = "/shippingInvoice/preShipping/orderTime",
  getOrderContent = "/business/platformOrder/queryPlatformOrderContentByMainId",
  listTransactions= '/transaction/listByClientAndCurrency',
  debit= '/transaction/debit',
  purchase= '/transaction/purchase',
  cancelInvoice = '/invoice/cancelInvoice',
}
