export enum Api {
  getClient = '/userClient/getClient',
  getClientTransactionCurrencies = '/transaction/getAllCurrenciesByClient',
  getBalance= '/balance/getBalanceByClientIdAndCurrency',
  getShops = '/shippingInvoice/shopsByClient',
  getSelfInvoiceShops = '/shippingInvoice/selfInvoiceShopsByClient',
  getShopOptions = '/shopOptions/findByClientId',
  getOrdersByShop = '/business/platformOrder/ordersByShop',
  postOrders = '/business/platformOrder/orderManagement',
  getRecipientInfo = '/business/platformOrder/recipientInfo',
  getOrderStatusByShop = "/shippingInvoice/preShipping/ordersStatusByShops",
  completeFeesEstimation = '/shippingInvoice/completeFeesEstimation',
  makeManualShippingInvoice = "/shippingInvoice/makeManualInvoice",
  makeManualPurchaseInvoice = "/shippingInvoice/makeManualPurchaseInvoice",
  makeCompleteManualInvoice = "/shippingInvoice/makeManualComplete",
  downloadInvoice = "/shippingInvoice/download",
  downloadPdf = "/generated/shippingInvoice/downloadPdf",
  downloadInvoiceDetail = "/shippingInvoice/downloadInvoiceDetail",
  getValidOrderTimePeriod = "/shippingInvoice/preShipping/orderTime",
  getOrderContent = "/business/platformOrder/queryPlatformOrderContentByMainId",
  listTransactions= '/transaction/listByClientAndCurrency',
  debit= '/transaction/debit',
  purchase= '/transaction/purchase',
  cancelInvoice = '/invoice/cancelInvoice',
  uploadPaymentProofAndNotify = '/transaction/uploadPaymentProofAndNotify',
  findEarliestInvoiceYear = '/invoice/findEarliestInvoiceYear',
  getOrderEstimations = '/shippingInvoice/completeFeesEstimationPerOrder',
}
